version: "3.9"
services:

  api-service:

    image: ${PROJECT_NAME}-${SERVICE_APP_NAME}:latest

    build:
      context: ..
      dockerfile: /deployments/app/Dockerfile

    container_name: ${PROJECT_NAME}-${SERVICE_APP_NAME}

    ports:
      - ${SERVER_PORT}:8080
    env_file:
      - .env
    networks:
      - application
    volumes:
      - 'app_data:/app'
    depends_on:
      - redis

  crontab-service:

    image: ${PROJECT_NAME}-${SERVICE_CRONTAB_NAME}:latest

    build:
      context: ..
      dockerfile: /deployments/crontab/Dockerfile

    container_name: ${PROJECT_NAME}-${SERVICE_CRONTAB_NAME}

    env_file:
      - .env
    networks:
      - application
    volumes:
      - 'app_data:/app'
    depends_on:
      - redis

  redis:
    image: 'bitnami/redis:latest'
    container_name: ${PROJECT_NAME}-${SERVICE_REDIS_NAME}
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=${REDIS_PORT}
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - application

networks:
  application:

volumes:
  redis_data:
    driver: local

  app_data:
    driver: local